# Generated by Django 3.1.6 on 2021-02-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Asked')),
                ('rank', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
